feat: make calendar
DEV-TINO/Mango-Diary-MJ pull request #2
Opened 2024-01-17 16:19 UTC by min-minnn

## Docs

- [이슈 보드 링크]()

## Changes

- before : 캘린더 UI만 구현
- after : 이번 달 기준으로 초기 캘린더 띄우고, 이전 달, 다음 달 캘린더 띄우기
- images

## Review Points

#### Problem

#### Solution

## Test Checklist

- [ ] check 1: 캘린더 구현
- [ ] check 2

2024-01-28 08:31 UTC, kim-song-jun requested changes
💯

2024-01-28 08:31 UTC, kim-song-jun commented on mj-diary/src/App.vue
> +    <router-link @click="this.$store.commit('submitDiary')" class="header-button-right" v-if="$route.path == `/write/${this.$store.state.writeDate}`" to="/main">
function -> condition?

2024-01-28 08:31 UTC, kim-song-jun commented on mj-diary/src/components/CalendarMainPage.vue
> +    <div class="last-month" @click="reloadCalendar(-1)">{{ this.$store.state.prev }}</div>
what is the paramter mean?

2024-01-28 08:31 UTC, kim-song-jun commented on mj-diary/src/components/CalendarMainPage.vue
> +    reloadCalendar(v) {
rename parameter

2024-01-28 08:31 UTC, kim-song-jun commented on mj-diary/src/store.js
> +      day: 0,
```
date : {
  year: 0,
  month: 0,
  day: 0
}
```

2024-01-28 08:31 UTC, kim-song-jun commented on mj-diary/src/components/CalendarWritePage.vue
> +        :class="{'colorMood': this.$store.state.todayMood == 'happiness', 'greyMood': this.$store.state.todayMood != 'happiness'}"
```vue
:class="imageMood"
```

```
imageMood(condition){
  return ...
}
```

2024-01-28 08:31 UTC, kim-song-jun commented on mj-diary/src/store.js
> +      prev: "<",
move to another component

2024-01-28 08:31 UTC, kim-song-jun commented on mj-diary/src/store.js
> +      today: new Date(),
move to another component

2024-01-28 08:31 UTC, kim-song-jun commented on mj-diary/src/store.js
> +    submitDiary(state) {
move to actions

2024-01-29 11:04 UTC, min-minnn commented
Done

2024-01-31 01:00 UTC, kim-song-jun approved these changes

2024-01-31 01:00 UTC, merged