feat: make statistics page and use API
DEV-TINO/Mango-Diary-MJ pull request #3
Opened 2024-01-31 12:53 UTC by min-minnn

## Docs

- [figma design templete](https://www.figma.com/file/0ByGSnJpm6DdAwqOrPSSeR/Mango-Diary?type=design&node-id=42-7&mode=design&t=Z7bveL6waZ3QQTGQ-0)

## Changes

- before : 
메인 캘린더 구현
글 작성 페이지 완성
뒤죽박죽한 클래스명
기본 폰트
함수를 이용한 header 버튼 조작
어느 날이든 다이어리 작성 가능(미래도 가능)
숫자로 월 표시하기
로컬에 데이터 저장해서 이미지 등의 경로 불러오기
일기를 작성하다가 통계 페이지로 넘어가면 다시 돌아왔을 때 작성하던 기록이 남아있음

- after :  
오늘 날짜 위치 표시
달력 디자인 변경
클래스명 규칙에 맞게 통일화
폰트 추가
mounted로 header 조작
현재 기준으로 미래 다이어리 작성 불가능하도록 만들기
약어로 월 표시
api 형식에 맞춰서 불러오기
통계 페이지 구현
일기 내용이 없거나 기분이 선택되지 않으면 submit이 불가능하도록
작성 중 통계 페이지로 넘어가면 작성하던 데이터가 지워지도록

- images
![localhost_5173_(iphone 14)](https://github.com/DEV-TINO/Mango-Diary-MJ/assets/59122931/3b42043c-daa5-43e0-a22f-56367c8acf12)
![localhost_5173_(iphone 14) (2)](https://github.com/DEV-TINO/Mango-Diary-MJ/assets/59122931/86f4ce29-8856-4591-aaea-c5cbe1266c46)
![localhost_5173_(iphone 14) (1)](https://github.com/DEV-TINO/Mango-Diary-MJ/assets/59122931/e0850755-5d70-4600-8c78-36292c02d68c)
![localhost_5174_statistics(iphone 14)](https://github.com/DEV-TINO/Mango-Diary-MJ/assets/59122931/ac0912a1-5052-4997-abd8-9ad16fd962ab)

## Review Points
- 오늘 날짜 위치 표시가 잘 되는가
- 임시 데이터 로직에 맞춰 수정했을 때 제대로 데이터가 불러와지는가
- 폰트가 잘 적용되는가
- header가 write 페이지에만 잘 뜨는가
- 미래 일기 작성이 불가능한가
- 데이터가 잘 저장이 되고, 수정이 되는가
- 일기가 존재하는 경우, 캘린더에 그날의 이모지가 잘 뜨는가

#### Problem
- 현재 날짜를 기준으로 미래의 일기는 작성 불가능하도록 하고 싶은데 달력 불러오는 과정에서 문제 발생
- 임시 데이터를 가지고 이미지를 렌더링하는 과정에서 이미지가 제대로 안 뜨는 현상이 발생
- 일기 내용이 없거나 기분이 선택되지 않았을 때 submit이 되지 않도록 하기
- 이미 일기가 존재하는 경우, 이모지 변경이 안 되는 경우가 생김

#### Solution
- 오늘의 날짜를 저장하는 객체와 달력 렌더링 시 필요한 날짜의 객체를 다르게 설정해서 해결
- 임시 데이터이기에, emoji_name을 가지고 이미지 렌더링
- router-link를 사용하지 않고 div로 변경 후 method 생성하여 관리
- selecedMood를 추가해서 변경할 수 있도록 함

## Test Checklist

- [x] check 1: 오늘 날짜 위치 표시
- [x] check 2: 통계 페이지 구현
- [x] check 3: API 형식에 맞춰서 수정
- [x] check 4: 달력 디자인 변경
- [x] check 5: style 클래스명 규칙 통일화
- [x] check 6: 폰트 추가
- [x] check 7: 과거와 현재 다이어리만 작성 가능
- [x] check 8: 다이어리에 선택한 이모지가 캘린더에 뜨게 하기
- [x] check 10: 일기 작성 및 저장
- [x] check 11: 일기 수정
- [x] check 12: 통계 페이지 데이터 적용
- [x]  check 13: 이모지 누끼 따기

2024-02-04 07:05 UTC, kim-song-jun requested changes
LGTM

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/App.vue
> +    <img :src="'/mood/' + this.$store.state.emojiData[0].emoji_name + '.png'" class="logo" />
change string format

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/components/CalendarMainPage.vue
> +      <div class="month">{{ this.$store.state.date.month_ENG }}</div>
change variable name

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/components/CalendarMainPage.vue
> +      <div class="month">{{ this.$store.state.date.month_ENG }}</div>
ENG_MONTH

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/components/CalendarMainPage.vue
> +        <tr :class="weekStyle(week)" v-for="week, index in this.$store.state.weeks" :key="index">
change name to `setWeekStyle()`

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/components/CalendarMainPage.vue
> +            <img v-if="setDay(day) != false" :src="'/mood/' + setDay(day).emoji_name + '.png'" class="calendarEmoji" />
change `src`

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/components/CalendarMainPage.vue
> +            <div v-if="setDay(day) == false" :class="today(day)">{{ day }}</div>
change function name to `setToday(day)`

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/components/CalendarMainPage.vue
> +  <div class="write-button" @click="goWrite(this.$store.state.todayDate.year, this.$store.state.todayDate.month, this.$store.state.todayDate.day)">write</div>
change function name to `handleClickWriteButton()`

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/components/CalendarMainPage.vue
> +    this.$store.state.showNavButton = false;
use `commit` method

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/components/CalendarMainPage.vue
> +      this.$store.state.writeYear = String(year);
use `commit` method

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/components/CalendarMainPage.vue
> +    },
add space between function

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/components/CalendarStatisticsPage.vue
> +      <div class="month">{{ this.$store.state.date.month_ENG }}</div>
change variable name

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/components/CalendarStatisticsPage.vue
> +    <div :class="setMoodBlock(statistics.statistic_rank)">
change to `camelCase`
do not `use snake_case` in js

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/components/CalendarStatisticsPage.vue
> +      <img :class="setMoodRank(statistics.statistic_rank)" :src="'/mood/' + this.$store.state.emojiData[statistics.statistic_emoji_id].emoji_name + '.png'" />
change `src`

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/components/CalendarStatisticsPage.vue
> +        <h3 :class="'top-count'">{{ this.$store.state.emojiData[statistics.statistic_emoji_id].emoji_subtitle }} {{ statistics.statistic_count }}개</h3>
add `?.` operator

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/components/CalendarStatisticsPage.vue
> +    this.$store.state.today = new Date();
use `commit` method

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/components/CalendarStatisticsPage.vue
> +    this.$store.state.today = new Date();
make init function in store.js
like this

```js
initToday(state) {
  state.today = new Date()
}
```

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/components/CalendarStatisticsPage.vue
> +    this.$store.state.showNavButton = false;
use `commit` function

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/components/CalendarWritePage.vue
> +          <img :src="'/mood/' + emoji.emoji_name + '.png'" :class="setImageMood(emoji)" @click="this.$store.commit('setMood', emoji)" />
change `src`

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/components/CalendarWritePage.vue
> +    this.$store.state.showNavButton = true;
see above

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/store.js
>        weeks: ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'],
move to top

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/store.js
> +        month_ENG: '',
change variable name

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/store.js
> +      emojiData: data.emoji,
make init function.

2024-02-04 07:05 UTC, kim-song-jun commented on mj-diary/src/store.js
> +      state.date.month_ENG = `${MONTH_MAP[state.date.month + 1]}`;
see above

2024-02-17 23:07 UTC, min-minnn commented
done

2024-02-17 23:13 UTC, min-minnn commented
done

2024-02-18 06:18 UTC, kim-song-jun approved these changes

2024-02-18 07:15 UTC, kim-song-jun reviewed
LGTM

2024-02-18 07:15 UTC, kim-song-jun commented on mj-diary/src/App.vue
> +    <img :src="`/mood/` + this.$store.state.emojiData[0].name + `.png`" class="logo" />
change to `/mood/${this.$store.state.emojiData[0].name}.png`

2024-02-18 07:15 UTC, kim-song-jun commented on mj-diary/src/App.vue
> +        this.$store.dispatch('submitDiary');
`dispatch` is promise object. 
use `async / await` to dispatch

2024-02-18 07:15 UTC, kim-song-jun commented on mj-diary/src/components/CalendarMainPage.vue
> +              <img :src="`/mood/` + setDays(day).name + `.png`" class="calendarEmoji" />
see above

2024-02-18 07:15 UTC, kim-song-jun commented on mj-diary/src/components/CalendarMainPage.vue
> +      this.$store.state.writeYear = String(year);
use `commit`

2024-02-18 07:15 UTC, kim-song-jun commented on mj-diary/src/components/CalendarMainPage.vue
> +      this.$store.state.writeDate = this.$store.state.writeYear + this.$store.state.wirteMonth + this.$store.state.writeDay;
use `commit` to change state.

2024-02-18 07:15 UTC, kim-song-jun commented on mj-diary/src/components/CalendarMainPage.vue
> +      if(week == 'SUN') {
```js
const weekMappingObject = {
   'SUN': 'sun',
   'SAT': 'sat'
}

return weekMappingObject?.[week] ?? 'week'
```

2024-02-18 07:15 UTC, kim-song-jun commented on mj-diary/src/components/CalendarStatisticsPage.vue
> +      <img :class="setMoodRank(index)" :src="`/mood/` + statistic.emoji + `.png`" />
see above

2024-02-18 07:15 UTC, kim-song-jun commented on mj-diary/src/components/CalendarWritePage.vue
> +          <img :src="`/mood/` + emoji.name + `.png`" :class="emojiClass(emoji.name)" @click="selectMood(emoji.name)" />
see above

2024-02-18 07:15 UTC, kim-song-jun commented on mj-diary/src/components/CalendarWritePage.vue
> +        <textarea class="text-write" @input="handleContentInput">{{ this.$store.state.postContent }}</textarea>
change to  `handleContentInput()`

2024-02-18 07:15 UTC, kim-song-jun commented on mj-diary/src/components/CalendarWritePage.vue
> +        this.$store.state.selectedMood = post.emoji;
use `commit`

2024-02-18 07:15 UTC, kim-song-jun commented on mj-diary/src/components/CalendarWritePage.vue
> +    this.loadPostData();
delete `;`

2024-02-18 07:15 UTC, kim-song-jun commented on mj-diary/src/data/data.js
> +	emoji: [
change `tab` to `space`

2024-02-24 16:02 UTC, min-minnn commented
done

2024-02-25 05:15 UTC, merged